version: '3'
services:

  flask-app:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: 'mysql'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_DB: 'devops'
    depends_on:
      - mysql
        
  mysql:
    container_name: 'mysql'
    image: 'mysql:5.7'
    ports:
       - "3306:3606"
    environment:
       MYSQL_ROOT_PASSWORD: 'root'
       MYSQL_DATABASE: 'devops'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
